default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: craftsy_development

test:
  <<: *default
  database: craftsy_test

production:
  <<: *default
  database: craftsy_production
  username: craftsy
  password: <%= ENV['EXAMPLE_DATABASE_PASSWORD'] %>
